"""empty message

Revision ID: 35afe1accf3f
Revises: 1bcbc05fa8c1
Create Date: 2025-03-15 14:47:06.847643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35afe1accf3f'
down_revision = '1bcbc05fa8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mitarbeiter')
    with op.batch_alter_table('meilenstein', schema=None) as batch_op:
        batch_op.alter_column('projektphase_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meilenstein', schema=None) as batch_op:
        batch_op.alter_column('projektphase_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('mitarbeiter',
    sa.Column('personalnummer', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('abteilung', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('arbeitspensum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('funktionen', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ist_kunde', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('personalnummer', name='mitarbeiter_pkey')
    )
    # ### end Alembic commands ###
