"""verwende einzelperson für aktivität

Revision ID: a236ef52e9b3
Revises: 2afc93328ded
Create Date: 2025-03-09 13:32:23.600902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a236ef52e9b3'
down_revision = '2afc93328ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('personelle_ressource')
    with op.batch_alter_table('aktivitaet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ressourcen', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'person', ['ressourcen'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aktivitaet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ressourcen')

    op.create_table('personelle_ressource',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aktivitaet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mitarbeiter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funktion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('budgetierte_zeit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('effektive_zeit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('abweichung', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('begruendung', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aktivitaet_id'], ['aktivitaet.id'], name='personelle_ressource_aktivitaet_id_fkey'),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['mitarbeiter.personalnummer'], name='personelle_ressource_mitarbeiter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='personelle_ressource_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('otp_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('two_factor_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('account_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###
