---
- name: Installiere Git (falls nicht vorhanden)
  apt:
    name: git
    state: present
    update_cache: yes

- name: Klone das Git-Repository
  git:
    repo: "git@github.com:Furerito/the_project.git"
    dest: "/var/www/the_project"
    version: master  # <-- Hier wird sichergestellt, dass der Branch "master" ausgecheckt wird
    accept_hostkey: yes
    force: yes
  become: yes
  become_user: "{{ ansible_user }}"

